### ISSUE TITLE
swiss vs athena

### ISSUE THREAD

**Issue by dret** [planetjekyll/awesome-jekyll-themes#7]
thanks for this great overview. but i am confused by the classification, or maybe just because i am trying to make things work on github. https://pages.github.com/themes/ says that there is only one supported theme on github, which is minima. when i played around with swiss, that seemed to work (but has curious limitations such as not allowing content on the home page?). then i tried to get away from that limitation and switched to athena, but that generated a github build error.
so maybe this is the wrong forum, but i think it would be very useful to add information about what works on github, because that may be something that a lot of people are curious about. thanks!

**Comment by geraldb** [comment]
sorry yes wrong forum. Please post to [jekyll talk](http://talk.jekyllrb.com). Good luck. Happy Jekylling. Cheers.
